Document: netfleet
Title: Debian netfleet Manual
Author: <insert document author here>
Abstract: This manual describes what netfleet is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/netfleet/netfleet.sgml.gz

Format: postscript
Files: /usr/share/doc/netfleet/netfleet.ps.gz

Format: text
Files: /usr/share/doc/netfleet/netfleet.text.gz

Format: HTML
Index: /usr/share/doc/netfleet/html/index.html
Files: /usr/share/doc/netfleet/html/*.html
